Import('env')

import os

currentPath = '.'

# Gets all the .cpp and.h files and puts them in a list
srcs = os.walk(currentPath)

print(srcs)

#Array of objects
objs = []

# Loops through source files
for roots, dirs, files in srcs:
	print("Files: " + str(files))
	print("Directories: " + str(dirs))

	for d in dirs:
		o = SConscript(root + "\\" + d + "\\SConscript")
		objs.extend(o)
	
	for f in files:
		if f.endswith(".cpp"):
			print(f)
			# Store as object, then add it to array
			o = env.Object(f)
			objs.extend(o)
	
#print("\n" + str(objs))
#Return array

#obj = env.Object('RenderManager.cpp')
Return('objs')